# Generated by Django 6.0.3 on 2026-03-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(help_text="For your reference.")),
                (
                    "code",
                    models.CharField(
                        help_text="The unique code for this MSO, which will be sent in SpecialMessage.xml entries for this MSO",
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The content of the special message."),
                ),
                (
                    "mso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_messages",
                        to="scmt.mso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friendlyName", models.CharField(max_length=100)),
                (
                    "heId",
                    models.CharField(
                        help_text="The unique ID for this STAR. Determiner of STAR this is.",
                        max_length=7,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "starType",
                    models.CharField(
                        choices=[
                            ("HD", "IntelliSTAR 2 HD (waow good for you)"),
                            ("JR", "IntelliSTAR 2 Jr"),
                            ("XD", "IntelliSTAR 2 xD"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        help_text="The locale of the unit according to the I2. For instance: 'N EVERETT'",
                        max_length=50,
                    ),
                ),
                (
                    "mso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scmt.mso"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Greeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        help_text="The first line of the greeting. This should be a short phrase that will be displayed on the STAR's screen.",
                        max_length=100,
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        help_text="The second line of the greeting. This should be a short phrase that will be displayed on the STAR's screen.",
                        max_length=100,
                    ),
                ),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greetings",
                        to="scmt.star",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AffiliateAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crawl_content",
                    models.TextField(
                        help_text="The content of the crawl for this ad. This should be a valid XML fragment that can be directly inserted into the AffiliateAds.xml template."
                    ),
                ),
                (
                    "friendlyName",
                    models.CharField(
                        help_text="A friendly name for this ad, for your reference.",
                        max_length=100,
                    ),
                ),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_ads",
                        to="scmt.star",
                    ),
                ),
            ],
        ),
    ]
