# Generated by Django 6.0.2 on 2026-03-06 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatead',
            options={'verbose_name': 'Ad Crawl'},
        ),
        migrations.AlterModelOptions(
            name='mso',
            options={'verbose_name': 'MSO'},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'verbose_name': 'STAR'},
        ),
        migrations.AddField(
            model_name='mso',
            name='specialmessage',
            field=models.TextField(blank=True, help_text='The content of the SpecialMessage.xml entry for this MSO. Leave blank for none.'),
        ),
        migrations.AlterField(
            model_name='mso',
            name='description',
            field=models.TextField(blank=True, help_text='For your reference.'),
        ),
        migrations.AlterField(
            model_name='star',
            name='friendlyName',
            field=models.CharField(max_length=100, verbose_name='Friendly Name'),
        ),
        migrations.AlterField(
            model_name='star',
            name='heId',
            field=models.CharField(help_text='The unique ID for this STAR. Must match HeadendId in your MPC.', max_length=7, unique=True, verbose_name='Headend ID'),
        ),
        migrations.AlterField(
            model_name='star',
            name='locale',
            field=models.CharField(help_text='Should match the place in HeadendName.', max_length=50),
        ),
        migrations.AlterField(
            model_name='star',
            name='mso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scmt.mso', verbose_name='MSO'),
        ),
        migrations.AlterField(
            model_name='star',
            name='starType',
            field=models.CharField(choices=[('HD', 'IntelliSTAR 2 HD (waow good for you)'), ('JR', 'IntelliSTAR 2 Jr'), ('XD', 'IntelliSTAR 2 xD')], max_length=2, verbose_name='STAR Type'),
        ),
        migrations.DeleteModel(
            name='SpecialMessage',
        ),
    ]
