# Generated by Django 6.0.3 on 2026-03-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmt', '0002_alter_affiliatead_options_alter_mso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatead',
            name='display_from',
            field=models.DateTimeField(blank=True, help_text='UNIMPLEMENTED - The date and time from which this ad should start being displayed on the STAR.', null=True),
        ),
        migrations.AddField(
            model_name='affiliatead',
            name='display_to',
            field=models.DateTimeField(blank=True, help_text='UNIMPLEMENTED - The date and time after which this ad should stop being displayed on the STAR.', null=True),
        ),
        migrations.AddField(
            model_name='affiliatead',
            name='is_mso_crawl',
            field=models.BooleanField(default=False, help_text="If ticked, this ad crawl will apply to all STARs from this ad crawl's MSO REGARDLESS of the content of the STAR field. If not ticked, this ad crawl will only apply to the STAR specified in the 'STAR' field."),
        ),
        migrations.AlterField(
            model_name='affiliatead',
            name='crawl_content',
            field=models.TextField(help_text='The content of the crawl for this ad.', max_length=280),
        ),
        migrations.AlterField(
            model_name='affiliatead',
            name='star',
            field=models.ForeignKey(blank=True, help_text="The STAR this ad crawl is associated with. Leave blank and tick the 'MSO Crawl' box for an ad crawl that applies to all STARs from this MSO.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_ads', to='scmt.star'),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='line2',
            field=models.CharField(blank=True, help_text="The second line of the greeting. This should be a short phrase that will be displayed on the STAR's screen.", max_length=100),
        ),
        migrations.AlterField(
            model_name='mso',
            name='code',
            field=models.CharField(help_text='The unique code for this MSO. Must match MsoCode in any MPCs for STARs from this MSO.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='mso',
            name='specialmessage',
            field=models.TextField(blank=True, help_text='The content of the SpecialMessage.xml entry for this MSO. Leave blank for none.', verbose_name='Special Message'),
        ),
    ]
