# Generated by Django 6.0.3 on 2026-03-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmt', '0003_affiliatead_display_from_affiliatead_display_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatead',
            name='dmaCode',
            field=models.CharField(blank=True, help_text='UNIMPLEMENTED - The DMA code that should match for this ad to be displayed. (e.g. 819 for Seattle-Tacoma)', max_length=10),
        ),
        migrations.AddField(
            model_name='affiliatead',
            name='stateCode',
            field=models.CharField(blank=True, help_text='UNIMPLEMENTED - The state code that should match for this ad to be displayed. (e.g. WA for Washington)', max_length=2),
        ),
        migrations.AddField(
            model_name='greeting',
            name='display_from',
            field=models.DateTimeField(blank=True, help_text='UNIMPLEMENTED - The date and time from which this ad should start being displayed on the STAR.', null=True),
        ),
        migrations.AddField(
            model_name='greeting',
            name='display_to',
            field=models.DateTimeField(blank=True, help_text='UNIMPLEMENTED - The date and time after which this ad should stop being displayed on the STAR.', null=True),
        ),
        migrations.AddField(
            model_name='greeting',
            name='dmaCode',
            field=models.CharField(blank=True, help_text='UNIMPLEMENTED - The DMA code that should match for this ad to be displayed. (e.g. 819 for Seattle-Tacoma)', max_length=10),
        ),
        migrations.AddField(
            model_name='greeting',
            name='stateCode',
            field=models.CharField(blank=True, help_text='UNIMPLEMENTED - The state code that should match for this ad to be displayed. (e.g. WA for Washington)', max_length=2),
        ),
        migrations.AddField(
            model_name='star',
            name='startRandomForCrawls',
            field=models.BooleanField(default=False, help_text='If ticked, the STAR will randomly pick a crawl instead of running through them sequentially.'),
        ),
        migrations.AddField(
            model_name='star',
            name='startRandomForGreetings',
            field=models.BooleanField(default=False, help_text='If ticked, the STAR will randomly pick a greeting instead of running through them sequentially.'),
        ),
        migrations.AlterField(
            model_name='mso',
            name='specialmessage',
            field=models.TextField(blank=True, help_text='The content of the SpecialMessage.xml entry for this MSO. This is a more consistent ad crawl, leave blank for none', verbose_name='Special Message'),
        ),
        migrations.CreateModel(
            name='SpecialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the entry')),
                ('mso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_messages', to='scmt.mso')),
            ],
        ),
    ]
