# Generated by Django 6.0.3 on 2026-04-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmt', '0004_affiliatead_dmacode_affiliatead_statecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatead',
            name='display_from',
            field=models.DateTimeField(blank=True, help_text='The date and time from which this ad should start being displayed on the STAR.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliatead',
            name='display_to',
            field=models.DateTimeField(blank=True, help_text='The date and time after which this ad should stop being displayed on the STAR.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliatead',
            name='dmaCode',
            field=models.CharField(blank=True, help_text='The DMA code that should match for this ad to be displayed. (e.g. 819 for Seattle-Tacoma)', max_length=10),
        ),
        migrations.AlterField(
            model_name='affiliatead',
            name='is_mso_crawl',
            field=models.BooleanField(default=False, help_text="If ticked, this ad crawl will apply to all STARs from this ad crawl's MSO REGARDLESS of the content of the STAR field. If not ticked, this ad crawl will only apply to the STAR specified in the 'STAR' field. [Mostly Unimplemented]"),
        ),
        migrations.AlterField(
            model_name='affiliatead',
            name='stateCode',
            field=models.CharField(blank=True, help_text='The state code that should match for this ad to be displayed. (e.g. WA for Washington)', max_length=2),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='display_from',
            field=models.DateTimeField(blank=True, help_text='The date and time from which this ad should start being displayed on the STAR.', null=True),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='display_to',
            field=models.DateTimeField(blank=True, help_text='The date and time after which this ad should stop being displayed on the STAR.', null=True),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='dmaCode',
            field=models.CharField(blank=True, help_text='The DMA code that should match for this ad to be displayed. (e.g. 819 for Seattle-Tacoma)', max_length=10),
        ),
        migrations.AlterField(
            model_name='greeting',
            name='stateCode',
            field=models.CharField(blank=True, help_text='The state code that should match for this ad to be displayed. (e.g. WA for Washington)', max_length=2),
        ),
        migrations.AlterField(
            model_name='star',
            name='startRandomForCrawls',
            field=models.BooleanField(default=False, help_text='If ticked, the STAR will randomly pick a crawl instead of running through them sequentially.', verbose_name='StartRandom - Crawls'),
        ),
        migrations.AlterField(
            model_name='star',
            name='startRandomForGreetings',
            field=models.BooleanField(default=False, help_text='If ticked, the STAR will randomly pick a greeting instead of running through them sequentially.', verbose_name='StartRandom - Greetings'),
        ),
        migrations.CreateModel(
            name='WxDotComPromoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the promo text')),
                ('display_from', models.DateTimeField(blank=True, help_text='The date and time from which this ad should start being displayed on the STAR.', null=True)),
                ('display_to', models.DateTimeField(blank=True, help_text='The date and time after which this ad should stop being displayed on the STAR.', null=True)),
                ('dmaCode', models.CharField(blank=True, help_text='The DMA code that should match for this ad to be displayed. (e.g. 819 for Seattle-Tacoma)', max_length=10)),
                ('stateCode', models.CharField(blank=True, help_text='The state code that should match for this ad to be displayed. (e.g. WA for Washington)', max_length=2)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wxpromotexts', to='scmt.star')),
            ],
            options={
                'verbose_name': 'Azul 7Day Fcst Message',
            },
        ),
    ]
