import requests
from django.shortcuts import render
from .models import Star, Mso, AffiliateAd, Greeting, WxDotComPromoText
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_GET

def affiliateads_xml(request, star_id):
    star = Star.objects.get(heId=star_id)
    affiliate_ads = AffiliateAd.objects.filter(star=star)
    crawls = [{"attrs": w.get_attributes(),
         "content": w.crawl_content,        }
        for w in affiliate_ads
    ]
    main_attr = star.get_startrandom_crawl()
    return render(request, "AffiliateAds.xml", {"crawls": crawls, "star_id": star_id, "main_attr": main_attr}, content_type="application/xml")

def lot8_WpTp_xml(request, star_id):
    star = Star.objects.get(heId=star_id)
    greetings = Greeting.objects.filter(star=star)
    wptps = [
        {"attrs": w.get_attributes(),
         "wptps": w.linebreak(),
        }
        for w in greetings
    ]
    main_attr = star.get_startrandom_greeting()
    return render(request, "LOT8WelcomeProductTextPhrases.xml", {"wptps": wptps, "star_id": star_id, "main_attr": main_attr}, content_type="application/xml")


def promotext_xml(request, star_id):
    star = Star.objects.get(heId=star_id)
    promotexts = WxDotComPromoText.objects.filter(star=star)
    promotext = [
        {"attrs": w.get_attributes(),
         "promo": w.message,
        }
        for w in promotexts
    ]
    return render(request, "WxDotComPromoText.xml", {"promotexts": promotext, "star_id": star_id}, content_type="application/xml")

def specialmessage_xml(request):
    # get all Mso records and build a list of dicts with code + message
    msos = Mso.objects.filter(specialmessage__isnull=False).exclude(specialmessage__exact='')
    events = [
        {"code": m.code,
         "message": m.specialmessage
        }
        for m in msos
    ]
    return render(request, "SpecialMessage.xml", {"events": events}, content_type="application/xml")

def ping(request):
    # return just "ok"
    return render(request, "ping.txt", content_type="application/text")


TWC_BASE_URL = "https://api.weather.com"
CREDIT = "Generated by STARstruck. A reimplementation of wx.lewolfyt.cc. Data sourced from The Weather Company."


# This SUUCKED to write, but now we can get around Comcast hating LeWolf and all his websites.
# This is a drop-in replacement for the wx.lewolfyt.cc API. The need for a decentralized version of this was evident so I made it!
# Wiki article on use (and on many other things around STARstruck) coming soon!
@require_GET
def weather_api(request):
    geo = request.GET.get("geo")
    icao = request.GET.get("icao")
    include_raw = request.GET.get("include")
    extendeddays_raw = request.GET.get("extendeddays")

    api_key = getattr(settings, "TWC_API_KEY", None)
    if not api_key:
        return JsonResponse(
            {
                "error": "TWC API key is not set for whatever reason - did you update your settings for 1.2?"},
            status=500,
        )

    if not geo and not icao:
        return JsonResponse(
            {
                "error": "Please specify either a geocode or an ICAO code with the geo or icao URL parameters respectively!"},
            status=400,
        )

    lat = lon = None
    if geo:
        try:
            lat_s, lon_s = geo.split(",")
            lat, lon = float(lat_s), float(lon_s)
        except ValueError:
            return JsonResponse({"error": "Geocode format incorrect, please specify it as lat,lon."}, status=400)

    if icao == "KDJT":
        kdjt_easter_egg = True
    else:
        kdjt_easter_egg = False

    extendeddays = 8
    if extendeddays_raw:
        try:
            extendeddays = int(extendeddays_raw)
        except ValueError:
            pass

    if include_raw:
        sections = set(s.strip() for s in include_raw.split(",") if s.strip())
    else:
        sections = {"current", "extended"}

    body = {"credit": CREDIT, "error": None}

    params = {
        "apiKey": api_key,
        "units": "e",
        "language": "en-US",
        "format": "json",
    }

    if icao:
        params["icaoCode"] = icao
    else:
        params["geocode"] = f"{lat},{lon}"

    try:
        if "current" in sections:
            resp = requests.get(
                f"{TWC_BASE_URL}/v3/wx/observations/current",
                params=params,
                timeout=10,
            )
            resp.raise_for_status()
            data = resp.json()

            if isinstance(data, list):
                data = data[0]

            info = {
                "phraseLong": data.get("wxPhraseLong"),
                "phraseShort": data.get("wxPhraseShort"),
                "phraseMedium": data.get("wxPhraseMedium"),
                "iconCode": data.get("iconCode"),
                "narrationCode": data.get("iconCodeExtend"),
                "weekday": data.get("dayOfWeek"),
                "dayOrNight": data.get("dayOrNight"),
                "expires": data.get("expirationTimeUtc"),
                "valid": data.get("validTimeUtc"),
                "sunrise": data.get("sunriseTimeUtc"),
                "sunset": data.get("sunsetTimeUtc"),
                "geocode": [lat, lon],
            }

            conditions = {
                "temperature": data.get("temperature"),
                "feelsLike": data.get("temperatureFeelsLike"),
                "heatIndex": data.get("temperatureHeatIndex"),
                "windChill": data.get("temperatureWindChill"),
                "dewPoint": data.get("temperatureDewPoint"),
                "tempMax24h": data.get("temperatureMax24Hour"),
                "tempMin24h": data.get("temperatureMin24Hour"),
                "tempMaxSince7Am": data.get("temperatureMaxSince7Am"),
                "tempChange24h": data.get("temperatureChange24Hour"),
                "pressure": data.get("pressureAltimeter"),
                "pressureSeaLevel": data.get("pressureMeanSeaLevel"),
                "pressureTendency": data.get("pressureTendencyCode"),
                "pressureTendencyPhrase": data.get("pressureTendencyTrend"),
                "precip1Hour": data.get("precip1Hour"),
                "precip6Hour": data.get("precip6Hour"),
                "precip24Hour": data.get("precip24Hour"),
                "snow1Hour": data.get("snow1Hour"),
                "snow6Hour": data.get("snow6Hour"),
                "snow24Hour": data.get("snow24Hour"),
                "humidity": data.get("relativeHumidity"),
                "visibility": data.get("visibility"),
                "windDirection": data.get("windDirection"),
                "windCardinal": data.get("windDirectionCardinal"),
                "windSpeed": data.get("windSpeed"),
                "windGusts": data.get("windGust"),
                "cloudCeiling": data.get("cloudCeiling"),
                "cloudCoverPhrase": data.get("cloudCoverPhrase"),
                "alerts": None,
            }

            body["current"] = {
                "info": info,
                "conditions": conditions,
            }

        if "extended" in sections:
            if extendeddays <= 2:
                duration = "3day"
            elif extendeddays <= 4:
                duration = "5day"
            elif extendeddays <= 6:
                duration = "7day"
            elif extendeddays <= 9:
                duration = "10day"
            else:
                duration = "15day"

            resp = requests.get(
                f"{TWC_BASE_URL}/v3/wx/forecast/daily/{duration}",
                params=params,
                timeout=10,
            )
            resp.raise_for_status()
            data = resp.json()

            n = len(data.get("validTimeUtc", []))
            daily = []

            for i in range(n):
                daily.append({
                    "weekday": data["dayOfWeek"][i],
                    "expires": data["expirationTimeUtc"][i],
                    "valid": data["validTimeUtc"][i],
                    "calendarTempMax": data["calendarDayTemperatureMax"][i],
                    "calendarTempMin": data["calendarDayTemperatureMin"][i],
                    "tempMax": data["temperatureMax"][i],
                    "tempMin": data["temperatureMin"][i],
                    "partiallyObserved": False,
                    "sunrise": data["sunriseTimeUtc"][i],
                    "sunset": data["sunsetTimeUtc"][i],
                    "moonrise": data["moonriseTimeUtc"][i],
                    "moonset": data["moonsetTimeUtc"][i],
                    "moonPhase": data["moonPhase"][i],
                    "moonPhaseCode": data["moonPhaseCode"][i],
                    "moonPhaseDay": data["moonPhaseDay"][i],
                    "precip": data["qpf"][i],
                    "snow": data["qpfSnow"][i],
                    "narration": data["narrative"][i],
                })

            daypart_block = data.get("daypart", [{}])[0]
            dp_n = len(daypart_block.get("daypartName", []))
            daypart = []

            for i in range(dp_n):
                name = daypart_block["daypartName"][i]
                if name is None:
                    continue

                daypart.append({
                    "name": name,
                    "dayOrNight": daypart_block["dayOrNight"][i],
                    "iconCode": daypart_block["iconCode"][i],
                    "narrationCode": daypart_block["iconCodeExtend"][i],
                    "narration": daypart_block["narrative"][i],
                    "precip": daypart_block["qpf"][i],
                    "snow": daypart_block["qpfSnow"][i],
                    "qualifier": daypart_block["qualifierCode"][i],
                    "qualifierPhrase": daypart_block["qualifierPhrase"][i],
                    "humidity": daypart_block["relativeHumidity"][i],
                    "temperature": daypart_block["temperature"][i],
                    "heatIndex": daypart_block["temperatureHeatIndex"][i],
                    "windChill": daypart_block["temperatureWindChill"][i],
                    "thunderCategory": daypart_block["thunderCategory"][i],
                    "thunderIndex": daypart_block["thunderIndex"][i],
                    "uvPhrase": daypart_block["uvDescription"][i],
                    "uvIndex": daypart_block["uvIndex"][i],
                    "windDirection": daypart_block["windDirection"][i],
                    "windCardinal": daypart_block["windDirectionCardinal"][i],
                    "windPhrase": daypart_block["windPhrase"][i],
                    "windSpeed": daypart_block["windSpeed"][i],
                    "phraseLong": daypart_block["wxPhraseLong"][i],
                    "phraseShort": daypart_block["wxPhraseShort"][i],
                })

            body["daily"] = daily
            body["daypart"] = daypart

            resp = requests.get(
                f"{TWC_BASE_URL}/v3/wx/forecast/hourly/2day",
                params=params,
                timeout=10,
            )
            resp.raise_for_status()
            data = resp.json()

            n = min(len(data.get("validTimeUtc", [])), 24)
            hourly = []

            for i in range(n):
                precip_type = data["precipType"][i]
                chance = data["precipChance"][i]

                hourly.append({
                    "weekday": data["dayOfWeek"][i],
                    "dayOrNight": data["dayOrNight"][i],
                    "iconCode": data["iconCode"][i],
                    "narrationCode": data["iconCodeExtend"][i],
                    "precip": data["qpf"][i],
                    "snow": data["qpfSnow"][i],
                    "ice": data["qpfIce"][i],
                    "qualifiers": [],
                    "humidity": data["relativeHumidity"][i],
                    "visibility": data["visibility"][i],
                    "temperature": data["temperature"][i],
                    "heatIndex": data["temperatureHeatIndex"][i],
                    "windChill": data["temperatureWindChill"][i],
                    "feelsLike": data["temperatureFeelsLike"][i],
                    "dewPoint": data["temperatureDewPoint"][i],
                    "pressure": data["pressureMeanSeaLevel"][i],
                    "wetBulbGlobe": None,
                    "cloudCeiling": None,
                    "rainChance": chance if precip_type == "rain" else 0,
                    "snowChance": chance if precip_type == "snow" else 0,
                    "sleetChance": chance if precip_type == "sleet" else 0,
                    "freezingRainChance": chance if precip_type == "freezingRain" else 0,
                    "thunderChance": None,
                    "uvPhrase": data["uvDescription"][i],
                    "uvIndex": data["uvIndex"][i],
                    "windDirection": data["windDirection"][i],
                    "windCardinal": data["windDirectionCardinal"][i],
                    "windGusts": data["windGust"][i],
                    "windSpeed": data["windSpeed"][i],
                    "phraseLong": data["wxPhraseLong"][i],
                    "phraseShort": data["wxPhraseShort"][i],
                    "expires": data["expirationTimeUtc"][i],
                    "valid": data["validTimeUtc"][i],
                    "severity": data["wxSeverity"][i],
                    "wxString": None,
                })

            body["hourly"] = hourly

        if "historical" in sections:
            resp = requests.get(
                f"{TWC_BASE_URL}/v3/wx/conditions/historical/dailysummary/30day",
                params=params,
                timeout=10,
            )
            resp.raise_for_status()
            data = resp.json()

            if isinstance(data, list):
                data = data[0]

            n = len(data.get("validTimeUtc", []))
            historical = []

            for i in range(min(n, 30)):
                historical.append({
                    "weekday": data["dayOfWeek"][i],
                    "dayIconCode": data["iconCodeDay"][i],
                    "dayNarrationCode": data["iconCodeExtendDay"][i],
                    "nightIconCode": data["iconCodeNight"][i],
                    "nightNarrationCode": data["iconCodeExtendNight"][i],
                    "precip24Hour": data["precip24Hour"][i],
                    "rain24Hour": data["rain24Hour"][i],
                    "snow24Hour": data["snow24Hour"][i],
                    "tempMin": data["temperatureMin"][i],
                    "tempMax": data["temperatureMax"][i],
                    "dayPhraseLong": data["wxPhraseLongDay"][i],
                    "dayPhraseNight": data["wxPhraseLongNight"][i],
                    "valid": data["validTimeUtc"][i],
                })

            body["historical"] = historical

    except requests.HTTPError as e:
        status = e.response.status_code if e.response is not None else 502
        try:
            detail = e.response.json()
        except Exception:
            detail = e.response.text if e.response is not None else str(e)
        return JsonResponse({"error": "API error.", "detail": detail}, status=status)
    except (KeyError, IndexError, TypeError) as e:
        return JsonResponse({"error": f"response mapping error: {e!r}"}, status=502)
    except requests.RequestException as e:
        return JsonResponse({"error": f"request failed: {e}"}, status=502)

    if kdjt_easter_egg:
        body["error"] = "Did you mean: KPBI"

    return JsonResponse(body)

# The django 404 page looks ugly so this is the other thing i wanted to take care of, adding a root page
def root_page(request):
    return render(request, template_name="starstruck_index.html")